# Generated by Django 4.0.3 on 2022-03-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('shipping', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
    ]
