# Generated by Django 4.0.3 on 2022-03-09 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_posted',
        ),
    ]
