# Generated by Django 4.0.3 on 2022-03-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_item_options_remove_item_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='location',
            new_name='city',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='main_app.item')),
            ],
        ),
    ]
