# Generated by Django 4.0.3 on 2022-03-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_photo_pic_remove_photo_url_photo_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='img',
        ),
        migrations.AddField(
            model_name='item',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
