# Generated by Django 4.0.3 on 2022-03-11 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_item_img_item_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pic',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
