# Generated by Django 4.0.3 on 2022-03-11 19:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_photo_name_photo_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='picture',
        ),
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='pic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.item'),
            preserve_default=False,
        ),
    ]
