# Generated by Django 4.0.3 on 2022-03-13 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0016_item_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='likes',
            field=models.ManyToManyField(related_name='item_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
