# Generated by Django 4.0.3 on 2022-03-13 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_item_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
