# Generated by Django 4.0.3 on 2022-03-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_remove_item_likes_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
