# Generated by Django 4.0.3 on 2022-03-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_item_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='header_image',
            new_name='photos',
        ),
    ]
