# Generated by Django 4.0.3 on 2022-03-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_rename_header_image_item_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
